// import localFont from "next/font/local";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }
// src/app/layout.js
// export const metadata = {
//   title: "Recurring Date Picker",
//   description: "A date picker with recurring options.",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         <main className="container mt-5">
//           <h1 className="text-center">Recurring Date Picker</h1>
//           {children}
//         </main>
//       </body>
//     </html>
//   );
// }
// src/app/layout.js
import { DateProvider } from "./context/DateContext";

export const metadata = {
  title: "Recurring Date Picker",
  description: "A date picker with recurring options.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <DateProvider>
          <main className="container mt-5">
            <h1 className="text-center">Recurring Date Picker</h1>
            {children}
          </main>
        </DateProvider>
      </body>
    </html>
  );
}
